/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OsCodOsRouteImport } from './routes/os.$codOs'
import { Route as CaminhaoTruckIdRouteImport } from './routes/caminhao.$truckId'
import { Route as OsCodOsIndexRouteImport } from './routes/os.$codOs.index'
import { Route as EtapaStageIdTruckIdRouteImport } from './routes/etapa.$stageId.$truckId'
import { Route as OsCodOsEtapaCodSituacaoRouteImport } from './routes/os.$codOs.etapa.$codSituacao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OsCodOsRoute = OsCodOsRouteImport.update({
  id: '/os/$codOs',
  path: '/os/$codOs',
  getParentRoute: () => rootRouteImport,
} as any)
const CaminhaoTruckIdRoute = CaminhaoTruckIdRouteImport.update({
  id: '/caminhao/$truckId',
  path: '/caminhao/$truckId',
  getParentRoute: () => rootRouteImport,
} as any)
const OsCodOsIndexRoute = OsCodOsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OsCodOsRoute,
} as any)
const EtapaStageIdTruckIdRoute = EtapaStageIdTruckIdRouteImport.update({
  id: '/etapa/$stageId/$truckId',
  path: '/etapa/$stageId/$truckId',
  getParentRoute: () => rootRouteImport,
} as any)
const OsCodOsEtapaCodSituacaoRoute = OsCodOsEtapaCodSituacaoRouteImport.update({
  id: '/etapa/$codSituacao',
  path: '/etapa/$codSituacao',
  getParentRoute: () => OsCodOsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/caminhao/$truckId': typeof CaminhaoTruckIdRoute
  '/os/$codOs': typeof OsCodOsRouteWithChildren
  '/etapa/$stageId/$truckId': typeof EtapaStageIdTruckIdRoute
  '/os/$codOs/': typeof OsCodOsIndexRoute
  '/os/$codOs/etapa/$codSituacao': typeof OsCodOsEtapaCodSituacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caminhao/$truckId': typeof CaminhaoTruckIdRoute
  '/etapa/$stageId/$truckId': typeof EtapaStageIdTruckIdRoute
  '/os/$codOs': typeof OsCodOsIndexRoute
  '/os/$codOs/etapa/$codSituacao': typeof OsCodOsEtapaCodSituacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/caminhao/$truckId': typeof CaminhaoTruckIdRoute
  '/os/$codOs': typeof OsCodOsRouteWithChildren
  '/etapa/$stageId/$truckId': typeof EtapaStageIdTruckIdRoute
  '/os/$codOs/': typeof OsCodOsIndexRoute
  '/os/$codOs/etapa/$codSituacao': typeof OsCodOsEtapaCodSituacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/caminhao/$truckId'
    | '/os/$codOs'
    | '/etapa/$stageId/$truckId'
    | '/os/$codOs/'
    | '/os/$codOs/etapa/$codSituacao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/caminhao/$truckId'
    | '/etapa/$stageId/$truckId'
    | '/os/$codOs'
    | '/os/$codOs/etapa/$codSituacao'
  id:
    | '__root__'
    | '/'
    | '/caminhao/$truckId'
    | '/os/$codOs'
    | '/etapa/$stageId/$truckId'
    | '/os/$codOs/'
    | '/os/$codOs/etapa/$codSituacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaminhaoTruckIdRoute: typeof CaminhaoTruckIdRoute
  OsCodOsRoute: typeof OsCodOsRouteWithChildren
  EtapaStageIdTruckIdRoute: typeof EtapaStageIdTruckIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os/$codOs': {
      id: '/os/$codOs'
      path: '/os/$codOs'
      fullPath: '/os/$codOs'
      preLoaderRoute: typeof OsCodOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caminhao/$truckId': {
      id: '/caminhao/$truckId'
      path: '/caminhao/$truckId'
      fullPath: '/caminhao/$truckId'
      preLoaderRoute: typeof CaminhaoTruckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os/$codOs/': {
      id: '/os/$codOs/'
      path: '/'
      fullPath: '/os/$codOs/'
      preLoaderRoute: typeof OsCodOsIndexRouteImport
      parentRoute: typeof OsCodOsRoute
    }
    '/etapa/$stageId/$truckId': {
      id: '/etapa/$stageId/$truckId'
      path: '/etapa/$stageId/$truckId'
      fullPath: '/etapa/$stageId/$truckId'
      preLoaderRoute: typeof EtapaStageIdTruckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os/$codOs/etapa/$codSituacao': {
      id: '/os/$codOs/etapa/$codSituacao'
      path: '/etapa/$codSituacao'
      fullPath: '/os/$codOs/etapa/$codSituacao'
      preLoaderRoute: typeof OsCodOsEtapaCodSituacaoRouteImport
      parentRoute: typeof OsCodOsRoute
    }
  }
}

interface OsCodOsRouteChildren {
  OsCodOsIndexRoute: typeof OsCodOsIndexRoute
  OsCodOsEtapaCodSituacaoRoute: typeof OsCodOsEtapaCodSituacaoRoute
}

const OsCodOsRouteChildren: OsCodOsRouteChildren = {
  OsCodOsIndexRoute: OsCodOsIndexRoute,
  OsCodOsEtapaCodSituacaoRoute: OsCodOsEtapaCodSituacaoRoute,
}

const OsCodOsRouteWithChildren =
  OsCodOsRoute._addFileChildren(OsCodOsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaminhaoTruckIdRoute: CaminhaoTruckIdRoute,
  OsCodOsRoute: OsCodOsRouteWithChildren,
  EtapaStageIdTruckIdRoute: EtapaStageIdTruckIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
